/**
 * Media harvester.
 *
 * The scraped source material (`raw messy data/info.md`) contains NO image URLs —
 * §4 of that report explicitly records that no logo was found and that the photo
 * libraries were never catalogued. So there is nothing belonging to the business to
 * download and localise.
 *
 * Instead we pull openly-licensed reference photography of the *dishes* from
 * Wikimedia Commons, record full attribution for every file, and optimise everything
 * to local AVIF/WebP. These are placeholders standing in for JeunJu's own photography;
 * `PHOTO-NEEDS.txt` (generated by scripts/photo-needs.mjs) is the shot list the client
 * shoots to replace them.
 *
 * Usage: node scripts/harvest-media.mjs
 */
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import sharp from 'sharp';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT_DIR = path.join(ROOT, 'public', 'media');
const CACHE_DIR = path.join(ROOT, '.media-cache');
/** Drop `<asset-id>.jpg` here to replace a placeholder with the client's own photo. */
const REPLACEMENTS_DIR = path.join(CACHE_DIR, 'replacements');
const MANIFEST = path.join(ROOT, 'src', 'content', 'media-manifest.json');

const UA = 'JeunJuSiteBuild/1.0 (https://github.com/; contact: owner via restaurant)';
const API = 'https://commons.wikimedia.org/w/api.php';

/**
 * Every asset we want, keyed by the id the site references it under.
 * `queries` are tried in order until one returns a usable file — Commons coverage of
 * specific Korean dishes is uneven, and a miss is fine (the UI degrades to a
 * typographic card rather than a broken image).
 */
const WANTED = [
  // ---- hero / atmosphere ----
  { id: 'hero-stew', kind: 'atmosphere', queries: ['Kimchi-jjigae', 'Kimchi stew'] },
  { id: 'atmos-banchan', kind: 'atmosphere', queries: ['Banchan', 'Korean side dishes'] },
  { id: 'atmos-jeonju', kind: 'atmosphere', queries: ['Jeonju Hanok Village', 'Jeonju'] },
  { id: 'atmos-onggi', kind: 'atmosphere', queries: ['Onggi', 'Jangdokdae'] },
  { id: 'atmos-table', kind: 'atmosphere', queries: ['Korean table setting', 'Hanjeongsik'] },

  // ---- mains ----
  { id: 'ssambap', kind: 'dish', queries: ['Ssambap', 'Bossam lettuce wrap'] },
  { id: 'dakdoritang', kind: 'dish', queries: ['Dak-bokkeum-tang', 'Dakdoritang'] },
  { id: 'la-galbi', kind: 'dish', queries: ['LA galbi', 'Galbi grilled'] },
  { id: 'bulgogi', kind: 'dish', queries: ['Bulgogi'] },
  { id: 'bibimbap', kind: 'dish', queries: ['Bibimbap'] },
  { id: 'godeungeo', kind: 'dish', queries: ['Godeungeo-gui', 'Grilled mackerel korean'] },
  { id: 'galchi', kind: 'dish', queries: ['Galchi-gui', 'Hairtail grilled'] },
  { id: 'jogi', kind: 'dish', queries: ['Jogi-gui', 'Croaker grilled'] },
  { id: 'ojingeo', kind: 'dish', queries: ['Ojingeo-gui', 'Grilled squid korean'] },

  // ---- soups & stews ----
  { id: 'ttaro-gukbap', kind: 'dish', queries: ['Ttaro-gukbap', 'Yukgaejang'] },
  { id: 'samgyetang', kind: 'dish', queries: ['Samgyetang'] },
  { id: 'kongnamul-gukbap', kind: 'dish', queries: ['Kongnamul-gukbap', 'Kongnamul guk'] },
  { id: 'haemul-sundubu', kind: 'dish', queries: ['Sundubu-jjigae'] },
  { id: 'haejangguk', kind: 'dish', queries: ['Haejangguk'] },
  { id: 'galbitang', kind: 'dish', queries: ['Galbi-tang'] },
  { id: 'gamjatang', kind: 'dish', queries: ['Gamja-tang'] },
  { id: 'kimchi-jjigae', kind: 'dish', queries: ['Kimchi-jjigae'] },
  { id: 'budae-jjigae', kind: 'dish', queries: ['Budae-jjigae'] },

  // ---- jeunju specials ----
  { id: 'kimchi-jeyuk', kind: 'dish', queries: ['Jeyuk-bokkeum', 'Dwaejigogi-bokkeum'] },
  { id: 'maeun-deungppyeo', kind: 'dish', queries: ['Deungppyeo-jjim', 'Gamja-tang'] },
  { id: 'gul-bossam', kind: 'dish', queries: ['Bossam', 'Gul-bossam'] },
  { id: 'daepae-samgyeop', kind: 'dish', queries: ['Samgyeopsal'] },
  { id: 'jjusam-bulgogi', kind: 'dish', queries: ['Nakji-bokkeum', 'Jjukkumi'] },
  { id: 'dakbal', kind: 'dish', queries: ['Dakbal'] },
  { id: 'gul-jeon', kind: 'dish', queries: ['Gul-jeon', 'Jeon korean food'] },
  { id: 'jeongol', kind: 'dish', queries: ['Jeongol'] },
  { id: 'makchang', kind: 'dish', queries: ['Makchang', 'Gopchang gui'] },
  { id: 'mugeunji-jeongol', kind: 'dish', queries: ['Mugeunji', 'Kimchi-jjim'] },

  // ---- noodles ----
  { id: 'kalguksu', kind: 'dish', queries: ['Kalguksu'] },
  { id: 'sujebi', kind: 'dish', queries: ['Sujebi'] },
  { id: 'jjolmyeon', kind: 'dish', queries: ['Jjolmyeon', 'Bibim-guksu'] },

  // ---- appetisers ----
  { id: 'gyeran-mari', kind: 'dish', queries: ['Gyeran-mari'] },
  { id: 'haemul-pajeon', kind: 'dish', queries: ['Haemul-pajeon', 'Pajeon'] },
  { id: 'kimchi-jeon', kind: 'dish', queries: ['Kimchi-jeon'] },
  { id: 'gun-mandu', kind: 'dish', queries: ['Gun-mandu', 'Fried mandu'] },
  { id: 'jjin-mandu', kind: 'dish', queries: ['Jjin-mandu', 'Mandu korean'] },
];

/** Widths we emit per asset. */
const WIDTHS = [480, 960, 1600];

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function api(params) {
  const url = `${API}?${new URLSearchParams({ ...params, format: 'json', origin: '*' })}`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Commons API ${res.status}`);
  return res.json();
}

/** Search Commons for a usable photo, returning url + attribution, or null. */
async function findImage(query) {
  const data = await api({
    action: 'query',
    generator: 'search',
    gsrsearch: `${query} filetype:bitmap`,
    gsrnamespace: '6',
    gsrlimit: '8',
    prop: 'imageinfo',
    iiprop: 'url|extmetadata|size|mime',
    iiurlwidth: '1600',
  });

  const pages = Object.values(data?.query?.pages ?? {});
  // Commons returns results in relevance order via `index`; respect it.
  pages.sort((a, b) => (a.index ?? 0) - (b.index ?? 0));

  for (const page of pages) {
    const info = page.imageinfo?.[0];
    if (!info) continue;
    if (!/^image\/(jpeg|png|webp)$/.test(info.mime ?? '')) continue;
    if ((info.width ?? 0) < 900) continue;

    const meta = info.extmetadata ?? {};
    const strip = (v) => (v ? String(v).replace(/<[^>]*>/g, '').trim() : '');
    const license = strip(meta.LicenseShortName?.value);
    // Skip anything without a clear reusable licence.
    if (!license || /fair use|non-free/i.test(license)) continue;

    return {
      source: 'Wikimedia Commons',
      file: page.title,
      pageUrl: `https://commons.wikimedia.org/wiki/${encodeURIComponent(page.title)}`,
      downloadUrl: info.thumburl ?? info.url,
      author: strip(meta.Artist?.value) || 'Unknown',
      license,
      licenseUrl: strip(meta.LicenseUrl?.value),
      width: info.thumbwidth ?? info.width,
      height: info.thumbheight ?? info.height,
    };
  }
  return null;
}

async function download(url) {
  const key = createHash('sha1').update(url).digest('hex');
  const cached = path.join(CACHE_DIR, `${key}.bin`);
  if (existsSync(cached)) return readFile(cached);

  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`download ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  await writeFile(cached, buf);
  return buf;
}

/**
 * Encode one source buffer into every width x format.
 *
 * Existing output is reused, so re-running is cheap — except when `force` is set, which
 * is how a client replacement overwrites the placeholder it is retiring.
 */
async function encode(id, buf, force = false) {
  const variants = [];
  const base = sharp(buf, { failOn: 'none' }).rotate();
  const meta = await base.metadata();

  for (const w of WIDTHS) {
    if (meta.width && meta.width < w && w !== WIDTHS[0]) continue;
    for (const [fmt, opts] of [
      ['avif', { quality: 52, effort: 4 }],
      ['webp', { quality: 76 }],
    ]) {
      const rel = `media/${id}-${w}.${fmt}`;
      const abs = path.join(ROOT, 'public', rel);
      if (force || !existsSync(abs)) {
        await sharp(buf, { failOn: 'none' })
          .rotate()
          .resize({ width: w, withoutEnlargement: true })
          .toFormat(fmt, opts)
          .toFile(abs);
      }
      variants.push({ width: w, format: fmt, src: `/${rel}` });
    }
  }

  // A tiny blurred base64 placeholder for zero-layout-shift loading.
  const blur = await sharp(buf, { failOn: 'none' })
    .rotate()
    .resize({ width: 16 })
    .blur(1.2)
    .webp({ quality: 40 })
    .toBuffer();

  return {
    variants,
    blurDataURL: `data:image/webp;base64,${blur.toString('base64')}`,
    aspectRatio: meta.width && meta.height ? +(meta.width / meta.height).toFixed(4) : 1.5,
  };
}

/**
 * The client's own photograph for an id, if they have dropped one in.
 * See PHOTO-NEEDS.txt — a file named `<id>.jpg` here wins over anything downloadable,
 * which is how placeholders get retired one at a time without touching any code.
 */
async function localReplacement(id) {
  for (const ext of ['jpg', 'jpeg', 'png', 'webp']) {
    const file = path.join(REPLACEMENTS_DIR, `${id}.${ext}`);
    if (existsSync(file)) return readFile(file);
  }
  return null;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  await mkdir(CACHE_DIR, { recursive: true });
  await mkdir(REPLACEMENTS_DIR, { recursive: true });
  await mkdir(path.dirname(MANIFEST), { recursive: true });

  /** Dedupe: two ids that resolve to the same Commons file share one encode. */
  const byFile = new Map();
  const assets = {};
  const missing = [];

  for (const want of WANTED) {
    // The client's own photo always wins — no search, no download, no attribution.
    const own = await localReplacement(want.id);
    if (own) {
      const encoded = await encode(want.id, own, true);
      assets[want.id] = {
        id: want.id,
        kind: want.kind,
        ...encoded,
        credit: null,
        ownPhotography: true,
      };
      console.log(`OWN   ${want.id}`);
      continue;
    }

    let found = null;
    for (const q of want.queries) {
      try {
        found = await findImage(q);
      } catch (err) {
        console.warn(`  ! ${want.id} "${q}": ${err.message}`);
      }
      if (found) break;
      await sleep(150);
    }

    if (!found) {
      console.warn(`MISS  ${want.id}`);
      missing.push(want.id);
      continue;
    }

    if (byFile.has(found.file)) {
      // Duplicate source photo — reuse the already-encoded asset.
      assets[want.id] = { ...byFile.get(found.file), duplicateOf: byFile.get(found.file).id };
      console.log(`DUP   ${want.id} <- ${found.file}`);
      continue;
    }

    try {
      const buf = await download(found.downloadUrl);
      const encoded = await encode(want.id, buf);
      const asset = {
        id: want.id,
        kind: want.kind,
        ...encoded,
        credit: {
          source: found.source,
          file: found.file,
          pageUrl: found.pageUrl,
          author: found.author,
          license: found.license,
          licenseUrl: found.licenseUrl,
        },
      };
      assets[want.id] = asset;
      byFile.set(found.file, asset);
      console.log(`OK    ${want.id}  (${found.license})`);
    } catch (err) {
      console.warn(`FAIL  ${want.id}: ${err.message}`);
      missing.push(want.id);
    }
    await sleep(120);
  }

  await writeFile(
    MANIFEST,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        note:
          'Placeholder reference photography from Wikimedia Commons. These are NOT photos of ' +
          "JeunJu's own food. Replace with the client's photography per PHOTO-NEEDS.txt.",
        missing,
        assets,
      },
      null,
      2,
    ) + '\n',
  );

  console.log(`\n${Object.keys(assets).length} assets, ${missing.length} missing.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
